main: net.tfminecraft.infestations.Infestations
api-version: '1.21.10'
name: Infestations
version: '${project.version}'
author: Drefvelin
depend: [TLibs, SimpleFactions, MythicMobs, ItemsAdder, InteractibleFurniture]

commands:
  infestation:
    description: Infestation admin commands
    usage: /infestation <reload|set|clear|list>
    aliases: [infestations]
    permission: infestations.admin

permissions:
  infestations.admin:
    description: Allows /infestation admin commands
    default: op
    children:
      infestations.admin.reload: true
  infestations.admin.reload:
    description: Reload Infestations configs
    default: op
